### PR TITLE
MIA Merged MRA Set

### PR DESCRIPTION
**Pull request by atrac17**
@furrtek I was going to look at dips and get them working if you don't mind.

### CODE REVIEW

**Comment by furrtek** [comment]
Please do. I double-checked the schematics but didn't find the cause of the reads returning incorrect values yet.

**Comment by atrac17** [comment]
> Please do. I double-checked the schematics but didn't find the cause of the reads returning incorrect values yet.

I'll see if I can get everything functional and push it with this commit. Might add the keyboard handler for mame we use in other cores too if you don't care. Makes testing so much easier.

**Comment by atrac17** [comment]
@furrtek I'm trying to see why DSW2 doesn't respond. It's setup right as far as I see in TMNT.v, everything else is functional now. I cleaned up the dips for 2P sets as well (coinage) in the MRA. I also placed everything in the files.qip instead of the tmnt.qsf and made an sdc. You can probably take this PR as is if you'd like.

**Comment by furrtek** [comment]
Thanks a lot ! Still trying to figure out why DSW2 isn't read properly.

**Comment by atrac17** [comment]
I looked at schematics, referenced mame, and tried a few different changes/builds to no avail.

**Pull request merged**
